site_name: lt's notes
site_url: https://626lt.github.io/
repo_name: 626lt/note
repo_url: https://github.com/626lt/note
site_description: "lt's notes"
dev_addr: '127.0.0.1:8001'
copyright: Copyright &copy; 2023-2024 <a href="https://github.com/626lt" target="_blank" rel="noopener">626lt</a>


theme: 
  name: 'material'
  custom_dir: overrides
  language: 'zh'
  icon: 
    logo: material/notebook-outline
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 日间模式
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
  font: false

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - admonition # mkdocs warning
  - md_in_html # footnote
  - meta # metadata
  - pymdownx.caret # underline
  - pymdownx.mark # text hightlight
  - pymdownx.tilde # strikethrough
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex: # TeX support for math formula
      generic: true
  - pymdownx.emoji: # emoji support
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.tasklist: # tasklist support
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables
#   - toc:
#       permalink: true
#       toc_depth: 4
#   - def_list
#   - attr_list
#   - sane_lists

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - css/custom.css
  - css/counter.css
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - js/katex.js
  - js/heti.js

plugins:
  - search
  - statistics:
      page_check_metadata: counter
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false
  # - tikzautomata

nav:
  - Home: index.md
  - CG:
    - cg/index.md
    - Introduction: cg/Intro/index.md
    - 2D Graphics: cg/2D Graphics/index.md
    - OpenGL: cg/OpenGL/index.md
    - Geometric Transformation: cg/Geometric Transformation/index.md
    - View: cg/View/index.md
    - Antialiasing: cg/Antialiasing/index.md
  - OS:
    - os/index.md
    - intro: os/intro/index.md
    - structures: os/structures/index.md
    - Threads: os/Threads/index.md
    - Synchronization: os/Synchronization/index.md
    - Deadlock: os/Deadlock/index.md
  - ML:
    - ml/index.md
    - probability graph: ml/probability graph/index.md
  - Read:
    - read/index.md
    - Diffusion: read/diffusion/index.md
    - Consistency Models: read/Consistency Models/index.md
    - SDE-Diffusion: read/SDE-diffusion/index.md
   